apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resources.amurant.io
spec:
  group: amurant.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              nonce:
                type: integer
              updated_at:
                type: string
  scope: Namespaced
  names:
    kind: Resource
    listKind: ResourceList
    plural: resources
    singular: resource
